package Metier;
// Generated 22 févr. 2015 15:49:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marque generated by hbm2java
 */
public class Marque  implements java.io.Serializable {


     private int codemarque;
     private String libellemarque;
     private String descriptionmarque;
     private Set modeles = new HashSet(0);

    public Marque() {
    }

	
    public Marque(int codemarque) {
        this.codemarque = codemarque;
    }
    public Marque(int codemarque, String libellemarque, String descriptionmarque, Set modeles) {
       this.codemarque = codemarque;
       this.libellemarque = libellemarque;
       this.descriptionmarque = descriptionmarque;
       this.modeles = modeles;
    }
   
    public int getCodemarque() {
        return this.codemarque;
    }
    
    public void setCodemarque(int codemarque) {
        this.codemarque = codemarque;
    }
    public String getLibellemarque() {
        return this.libellemarque;
    }
    
    public void setLibellemarque(String libellemarque) {
        this.libellemarque = libellemarque;
    }
    public String getDescriptionmarque() {
        return this.descriptionmarque;
    }
    
    public void setDescriptionmarque(String descriptionmarque) {
        this.descriptionmarque = descriptionmarque;
    }
    public Set getModeles() {
        return this.modeles;
    }
    
    public void setModeles(Set modeles) {
        this.modeles = modeles;
    }




}


