package Metier;
// Generated 22 févr. 2015 15:49:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modele generated by hbm2java
 */
public class Modele  implements java.io.Serializable {


     private int codemodele;
     private Marque marque;
     private String libellemodele;
     private String descriptionmodele;
     private Set vehicules = new HashSet(0);

    public Modele() {
    }

	
    public Modele(int codemodele, Marque marque) {
        this.codemodele = codemodele;
        this.marque = marque;
    }
    public Modele(int codemodele, Marque marque, String libellemodele, String descriptionmodele, Set vehicules) {
       this.codemodele = codemodele;
       this.marque = marque;
       this.libellemodele = libellemodele;
       this.descriptionmodele = descriptionmodele;
       this.vehicules = vehicules;
    }
   
    public int getCodemodele() {
        return this.codemodele;
    }
    
    public void setCodemodele(int codemodele) {
        this.codemodele = codemodele;
    }
    public Marque getMarque() {
        return this.marque;
    }
    
    public void setMarque(Marque marque) {
        this.marque = marque;
    }
    public String getLibellemodele() {
        return this.libellemodele;
    }
    
    public void setLibellemodele(String libellemodele) {
        this.libellemodele = libellemodele;
    }
    public String getDescriptionmodele() {
        return this.descriptionmodele;
    }
    
    public void setDescriptionmodele(String descriptionmodele) {
        this.descriptionmodele = descriptionmodele;
    }
    public Set getVehicules() {
        return this.vehicules;
    }
    
    public void setVehicules(Set vehicules) {
        this.vehicules = vehicules;
    }




}


