package Metier;
// Generated 22 f�vr. 2015 15:49:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vehicule generated by hbm2java
 */
public class Vehicule  implements java.io.Serializable {


     private String matricule;
     private Modele modele;
     private String noimputation;
     private String typeacquisition;
     private String nocartegrise;
     private Date datemisecirculation;
     private String now;
     private Double poids;
     private String carburant;
     private String nochassis;
     private Integer nbrplaces;
     private String confort;
     private String couleur;
     private Date daterestitution;
     private String ancienmatricule;

    public Vehicule() {
    }

    public Vehicule(String matricule) {
        this.matricule = matricule;
    }

	
    public Vehicule(String matricule, Modele modele) {
        this.matricule = matricule;
        this.modele = modele;
    }
    public Vehicule(String matricule, Modele modele, String noimputation, String typeacquisition, String nocartegrise, Date datemisecirculation, String now, Double poids, String carburant, String nochassis, Integer nbrplaces, String confort, String couleur, Date daterestitution, String ancienmatricule) {
       this.matricule = matricule;
       this.modele = modele;
       this.noimputation = noimputation;
       this.typeacquisition = typeacquisition;
       this.nocartegrise = nocartegrise;
       this.datemisecirculation = datemisecirculation;
       this.now = now;
       this.poids = poids;
       this.carburant = carburant;
       this.nochassis = nochassis;
       this.nbrplaces = nbrplaces;
       this.confort = confort;
       this.couleur = couleur;
       this.daterestitution = daterestitution;
       this.ancienmatricule = ancienmatricule;
    }
   
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }
    public Modele getModele() {
        return this.modele;
    }
    
    public void setModele(Modele modele) {
        this.modele = modele;
    }
    public String getNoimputation() {
        return this.noimputation;
    }
    
    public void setNoimputation(String noimputation) {
        this.noimputation = noimputation;
    }
    public String getTypeacquisition() {
        return this.typeacquisition;
    }
    
    public void setTypeacquisition(String typeacquisition) {
        this.typeacquisition = typeacquisition;
    }
    public String getNocartegrise() {
        return this.nocartegrise;
    }
    
    public void setNocartegrise(String nocartegrise) {
        this.nocartegrise = nocartegrise;
    }
    public Date getDatemisecirculation() {
        return this.datemisecirculation;
    }
    
    public void setDatemisecirculation(Date datemisecirculation) {
        this.datemisecirculation = datemisecirculation;
    }
    public String getNow() {
        return this.now;
    }
    
    public void setNow(String now) {
        this.now = now;
    }
    public Double getPoids() {
        return this.poids;
    }
    
    public void setPoids(Double poids) {
        this.poids = poids;
    }
    public String getCarburant() {
        return this.carburant;
    }
    
    public void setCarburant(String carburant) {
        this.carburant = carburant;
    }
    public String getNochassis() {
        return this.nochassis;
    }
    
    public void setNochassis(String nochassis) {
        this.nochassis = nochassis;
    }
    public Integer getNbrplaces() {
        return this.nbrplaces;
    }
    
    public void setNbrplaces(Integer nbrplaces) {
        this.nbrplaces = nbrplaces;
    }
    public String getConfort() {
        return this.confort;
    }
    
    public void setConfort(String confort) {
        this.confort = confort;
    }
    public String getCouleur() {
        return this.couleur;
    }
    
    public void setCouleur(String couleur) {
        this.couleur = couleur;
    }
    public Date getDaterestitution() {
        return this.daterestitution;
    }
    
    public void setDaterestitution(Date daterestitution) {
        this.daterestitution = daterestitution;
    }
    public String getAncienmatricule() {
        return this.ancienmatricule;
    }
    
    public void setAncienmatricule(String ancienmatricule) {
        this.ancienmatricule = ancienmatricule;
    }




}


